### ISSUE TITLE
WS eXECUTION SAYS no connected clients when is running

### ISSUE THREAD

**Issue by ZkyRPT** [lncoognito/Roblox-WS#3]

**Comment by lncoognito** [comment]
This problem is due to krampus injecting too fast and auto-exec not running  because of that.
I can do nothing to solve this sadly, this is a krampus issue.

**Comment by lncoognito** [comment]
This problem is due to krampus injecting too fast and auto-exec not running because of that.
I can do nothing to solve this sadly, this is a krampus issue.
or maybe you forgot to use the Client.lua provided on the github page.
